export const serverUrl = 'https://rbs-back.glitch.me'

export const blackSea_1 = [
    'The most popular assumption about the origin of the name "Black Sea" is that it comes from the dark color of the water (The waters of the Black Sea are generally darker than the waters of the Azov, Marmara and Aegean seas.).',
    'The Black Sea is a marginal mediterranean sea lying between Europe and Asia, east of the Balkans, south of the East European Plain, west of the Caucasus, and north of Anatolia. It is bounded by Bulgaria, Georgia, Romania, Russia, Turkey, and Ukraine. The Black Sea is supplied by major rivers, principally the Danube, Dnieper and Don. Consequently, while six countries have a coastline on the sea, its drainage basin includes parts of 24 countries in Europe.'
]
export const blackSea_2 = 'The Black Sea covers 436,400 sq km (168,500 sq mi) (not including the Sea of Azov), has a maximum depth of 2,212 m (7,257 ft), and a volume of 547,000 cu km (131,000 cu mi). Most of its coasts ascend rapidly. These rises are the Pontic Mountains to the south, bar the southwest-facing peninsulas, the Caucasus Mountains to the east, and the Crimean Mountains to the mid-north. In the west, the coast is generally small floodplains below foothills such as the Strandzha; Cape Emine, a dwindling of the east end of the Balkan Mountains; and the Dobruja Plateau considerably farther north. The longest east-west extent is about 1,175 km (730 mi).'
export const blackSea_3 = [
    'The area surrounding the Black Sea is commonly referred to as the Black Sea Region. Its northern part lies within the Chernozem belt (black soil belt) which goes from eastern Croatia (Slavonia), along the Danube (northern Serbia, northern Bulgaria (Danubian Plain) and southern Romania (Wallachian Plain)) to northeast Ukraine and further across the Central Black Earth Region and southern Russia into Siberia.',
    'The littoral zone of the Black Sea is often referred to as the Pontic littoral or Pontic zone.',
    'The largest bays of the Black Sea are Karkinit Bay in Ukraine; the Gulf of Burgas in Bulgaria; Dnieprovski Bay and Dniestrovski Bay, both in Ukraine; and Sinop Bay and Samsun Bay, both in Turkey.',
    'Short-term climatic variation in the Black Sea region is significantly influenced by the operation of the North Atlantic oscillation, the climatic mechanisms resulting from the interaction between the north Atlantic and mid-latitude air masses. While the exact mechanisms causing the North Atlantic Oscillation remain unclear, it is thought the climate conditions established in western Europe mediate the heat and precipitation fluxes reaching Central Europe and Eurasia, regulating the formation of winter cyclones, which are largely responsible for regional precipitation inputs and influence Mediterranean sea surface temperatures. The relative strength of these systems also limits the amount of cold air arriving from northern regions during winter. Other influencing factors include the regional topography, as depressions and storm systems arriving from the Mediterranean are funneled through the low land around the Bosporus, with the Pontic and Caucasus mountain ranges acting as waveguides, limiting the speed and paths of cyclones passing through the region.',
    'The average salinity of water in the Black Sea is about 18 ppm (for comparison, in the Mediterranean Sea - 37 ppm), near river estuaries - less than 9 ppm. At a depth of 90-120 m there is a layer of water with rapidly changing salinity (halocline). Salinity in this depth range increases from 18.5 to 21.5 ppm. At the bottom, salinity reaches 22.3 ppm.',
    'One of the main features of the Black Sea is hydrogen sulfide: at a depth of over 200 meters there is so much of it that only some types of anaerobic bacteria can survive. The complete absence of oxygen completely prevents animals and algae from living there, and hydrogen sulfide itself paralyzes the cellular respiration of organisms. At depths of 150-200 meters there is a chemocline, that is, a layer of sharp changes in the hydrochemical parameters of water (primarily, this is the transition between the oxygen and hydrogen sulfide zones).',
    'Two masses of Black Sea water: surface (with low salinity, rich in oxygen and close in temperature to air) and deep (more salty and dense, with a constant temperature, oxygen-free (anaerobic zone)), are separated by a boundary layer of water located at depths of 30 up to 100 m (the so-called cold intermediate layer, or CIL). Its temperature is always lower than that of deep waters, since, cooling in winter, it does not have time to warm up during the summer.',
    'The flora of the sea includes 270 species of multicellular green, brown, and red bottom algae. The phytoplankton of the sea contains at least six hundred species.',
    'The fauna of the Black Sea is noticeably poorer than the Mediterranean, in particular, there are no starfish, sea urchins, crinoids (sea lilies), octopuses, cuttlefish, squid or corals. The Black Sea is home to 2,500 species of animals (of which 500 species are unicellular, about 200 species of vertebrates - fish and mammals, 500 species of crustaceans, 200 species of mollusks, the rest are invertebrates of various species). The main reasons for this are the low salinity of the water and the constant presence of hydrogen sulfide at depths of more than 150 m.',
    'Marine mammals present within the basin include two species of dolphin (common and bottlenose) and the harbour porpoise, although all of these are endangered due to pressures and impacts by human activities. All three species have been classified as distinct subspecies from those in the Mediterranean and the Atlantic and are endemic to the Black and Azov seas, and are more active during nights in the Turkish Straits.',
    'Common fish in the Black Sea are various types of gobies, european anchovy, Black Sea spiny dogfish, Black Sea turbot, mullets (5 species), bluefish, european hake, black scorpionfish, Atlantic mackerel, Black Sea sprat, Mediterranean horse mackerel, garfish, seahorse and others. Dangerous fish of the Black Sea are: greater weever (the most dangerous - the spines of the dorsal fin and gill covers are poisonous), black scorpionfish (the spines contain poison), common stingray (with poisonous spines on the tail). Another stingray - thornback ray - is non-venomous, but is covered with spines, especially on the tail; defending itself, it can inflict a large number of thrusts and scratches.',
    'At the bottom of the Black Sea live mussels, oysters, scallops, as well as the predator mollusk veined rapa whelk, brought by vessels from the Far East, which, due to the absence of natural enemies, multiplied and exterminated some and brought other mollusks (oysters, flexopecten glabers) to the brink of extinction. Numerous crabs and shrimp live in the crevices of coastal rocks and among stones.',
    'Barrel jellyfish and common jellyfish are widespread among jellyfish.'
]